name = "Raven"
uuid = "0ecc78c5-42b8-4664-97dc-55e6808aaa3c"

[deps]
FunctionalCollections = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
LNR = "7c4cb9fa-83a0-5386-9231-d6167c818060"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
WebAssembly = "4f6df8df-4739-5653-a877-cf57ee625c27"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
