name: CI

on:
  push:
    branches: [ '**' ] # Run on all branch pushes
  pull_request:
    branches: [ master ] # Keep pull request behavior the same

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [24.9]
        os:
          - ubuntu-latest
          - windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "17"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - uses: bytecodealliance/actions/wasm-tools/setup@v1
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - run: 'npm install --global wabt'

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npx tsc

    - name: Run tests
      run: npm test
